# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: | 
    echo Hello, world!
   
    docker run --name hackyswordpress -d conetix/wordpress-with-wp-cli 
    docker exec hackyswordpress wp config create
    docker exec hackyswordpress wp theme install quark

  displayName: 'Install Wordpress Cli'



